apiVersion: v1
kind: ConfigMap
metadata:
  name: url-service-config
  namespace: urlshortener
data:
  BASE_URL: "http://urlshortener.local"
  DEBUG: "false"
  CORS_ORIGINS: "http://localhost,http://urlshortener.local"
  ANALYTICS_SERVICE_URL: "http://analytics-service:3001"
  REDIS_URL: "redis://redis:6379"
